apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:latest
          ports:
            - containerPort: 80
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/webapp_production"
