name: Docker Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Build Docker Image
      run: |
        docker build -t webapp:latest .

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0
      with:
        cluster_name: kind
    - name: Load Docker Image into Kind
      run: kind load docker-image webapp:latest --name kind

    - name: Load Docker Image to KinD
      run: |
        kind load docker-image webapp:latest

    - name: Build and start containers for a services
      run: |
        kubectl apply -R -f ./k8s
        kubectl wait pods --all --for condition=Ready
    - name: Port Forward to webservice
      run: kubectl port-forward service/webapp-service 8080:80 &
    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
      with:
        working-directory: ./.github/tests
